services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf

    restart: unless-stopped

    ports:
      - "13378:80"

    environment:
      TZ: America/New_York

    volumes:
      - /mnt/audiobooks/Books:/audiobooks
      - /mnt/audiobooks/ebooks:/ebooks
      - /opt/homelab/audiobookshelf/config:/config
      - /opt/homelab/audiobookshelf/metadata:/metadata